### PR TITLE
Tip: Cleanup Dockerfile

### PR DESCRIPTION
**Pull request by sammcj**
Trying to make everything slightly less, um... disgusting here.
I'm not actually using this, but I thought I'd suggest a few things (that you will need to test) to help improve your Docker experience.

Further suggestions:

* Use supervisor to manage php-fpm and nginx inside the container
* Run as a user other than root (even though this is in a container)
* Upstream from Debian rather than Ubuntu
* Consider if you *really* need vim, curl, wget, build-essential inside your image...

### CODE REVIEW

**Comment by sammcj** [comment]
Note: Do not merge this as-is, feel free to check it out and learn from it / fix it and make it better for yourself - just trying to help out.

**Comment by fideloper** [comment]
Uh, right. I mean, I appreciate it, I guess, except for the condescension.

I should expand on that - this is a 1 year old repository. I've learned a
lot more about docker since It's been created. This just feels
condescending based on your assumption that it represents my current usage
of Docker. I can see how your just trying to help...other than calling the
code disgusting :P

This was my first stab at docker, unused on my end. I'd blow it away if I
didn't think the few who PRed to it might be using using it.

I'd otherwise agree with you in your points. I just don't care to maintain
this, so I'll either delete it or note that in a readme.

May I ask how you came across this? I might have linked it from a SFH
article which I could see leading you to believe that I think it's relevant
still.

Thanks

**Comment by sammcj** [comment]
Oh my, I don't know what I was thinking when I wrote that - please accept my sincere apologies for my wording there - I was on a roll cleaning up some docker files I had then I needed a Nginx php image to test something really quickly internally - saw this and thought 'I'll just make a few quick cleanup changes...'  

I shouldn't have used the word disgusting - but my intentions were good - sorry to oftend (- I'm embarrassed I wrote that.

**Comment by fideloper** [comment]
Hey Sam!

I appreciate you writing back, I had a feeling you didn't mean it like
that, but I guess that's how it sounded to me.

No harm done!

I do totally agree with your points, but in the end I just don't care
enough (or more accurately, have the time care) about this repo to take
action and make changes to it (I think some users might be using it, and
expect it to work this way, but I'm not sure on usage at all).

When I get more free time to come back to Docker stuff I'll probably create
a few new ones which are more inline with these ideas. (We'll see ! So far
I haven't used it in production much, I haven't had the need to really
containerize stuff in production in a day to day job or side project).

Thanks for hearing me out :D

**Pull request closed without merging**
